FROM ubuntu:22.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && apt install -y software-properties-common
RUN add-apt-repository -y ppa:ondrej/php && apt update
RUN apt install -y --no-install-recommends  git php8.1-dev liblzma-dev build-essential
RUN git clone https://github.com/codemasher/php-ext-xz.git && cd php-ext-xz && phpize && ./configure && make
